### ISSUE TITLE
Impossible seed.

### ISSUE THREAD

**Issue by KrakenTheJaken** [adrienntindall/hgss-map-randomizer#21] opened 2022-06-06 00:28 UTC
In this seed the entrance to slowpoke well was a dead end.

[rando.nds_map_randomized.log](https://github.com/adrienntindall/hgss-map-randomizer/files/8841093/rando.nds_map_randomized.log)

https://user-images.githubusercontent.com/58538619/172076940-8c4ab7fd-cefd-40f5-b9a5-a0264a5ce74e.mp4

**Comment by adrienntindall** [comment] 2022-06-06 02:03
What likely happened is that the game put cut behind surf and strength, and I was going to close this as not a bug... but upon further testing it looks like that's a hard lock because the NPC prevents the strength bolder from being pushed enough for you to get through. This has been accounted for in the logic now, thank you for bringing it to my attention

**Closed by adrienntindall** 2022-06-06 02:03 UTC

**Comment by KrakenTheJaken** [comment] 2022-06-06 02:11
To clarify instead of you being required to find 31 loading zones,  (as stated in misc info), do you only need to find 28 (minus ilex, well, & theater) because of the hm change?

**Comment by adrienntindall** [comment] 2022-06-06 03:07
You still need to find everything, the logic changes only affect the order that you can obtain HMs in, so it won't always be Cut -> Strength -> Surf -> etc
Now you might need surf to access cut, rock climb to get strength, etc. 
The logic takes this into account and makes sure that Surf is obtainable before Misty and Cut is obtainable before Erika, since those are the earliest points where either is required for every single seed.
