### ISSUE TITLE
Randomized rooms not exiting properly

### ISSUE THREAD

**Issue by kaetakara** [adrienntindall/hgss-map-randomizer#1] opened 2022-05-04 22:56 UTC
Randomized a HG rom and ran into multiple instances where I was exiting incorrectly. Entered into a door in New Bark Town. Came out of a ladder in a cave. Went back up the ladder and it exits me inside the house where I cannot move. The only way I can move is down which takes me back through the door and down the ladder. I have tried both sides of the ladder and same issue.

**Comment by adrienntindall** [comment] 2022-05-04 23:02
This was caused by a Cygwin dependency ("cp command not found") and has been fixed in the latest release, though you will have to rerandomize your seed

**Closed by adrienntindall** 2022-05-04 23:02 UTC
